"""add sync stats columns to sync_run

Revision ID: 6b499b328700
Revises: 1a80947041f8
Create Date: 2026-04-06 11:11:04.819764
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6b499b328700'
down_revision: Union[str, None] = '1a80947041f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_run', sa.Column('books_new', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sync_run', sa.Column('books_updated', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sync_run', sa.Column('books_failed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_run', 'books_failed')
    op.drop_column('sync_run', 'books_updated')
    op.drop_column('sync_run', 'books_new')
    # ### end Alembic commands ###
